<a href="https://colab.research.google.com/github/osmarbraz/exemplos_python/blob/master/ExemplosPythonAlgebraLinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exemplos Vetores, Matrizes e Álgebra Linear em Python no Google Colaboratory

Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares, sejam elas algébricas ou diferenciais. A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes.

Exemplos:
- Vetor padrão;
- Matriz padrão;
- Matriz com NumPy.

-----------------------------------------
**Guia Colab Iniciante:**

https://medium.com/machina-sapiens/google-colab-guia-do-iniciante-334d70aad531

**Documentação oficial:**

https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.01-Help-And-Documentation.ipynb

**Características :**

https://colab.research.google.com/notebooks/basic_features_overview.ipynb

# Vetor Padrão

Inicialização vetor

In [ ]:
A = [1,2,3]

print(A)

[1, 2, 3]


Mutiplicando vetor por constante

In [ ]:
A = [1, 2]

B = A *  3

print(A)
print('A * 3 = ' + str(B))

[1, 2]
A * 3 = [1, 2, 1, 2, 1, 2]


# Matriz Padrão

Inicialização matriz

In [ ]:
A = [[1,2,3],[4,5,6],[7,8,9]]

print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Mutiplicando matriz por constante

In [ ]:
A = [[1,2],[3,4]]

B = A * 3

print(A)
print('A * 3 = ' + str(B))

[[1, 2], [3, 4]]
A * 3 = [[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]]


Mutiplicando elementos do vetor por constante

In [ ]:
A = [1 , 2]
B = [i * 3.0 for i in A]

print(A)
print('A * 3 = ' + str(B))

[1, 2]
A * 3 = [3.0, 6.0]


# Matriz com NumPy

É um pacote para linguagem Python que possibilita realizar diversas operação com vetores e matrizes de forma rápida e eficiente.

http://www.estruturas.ufpr.br/disciplinas/pos-graduacao/introducao-a-computacao-cientifica-com-python/introducao-python/2-2-operacoes-numericas-com-arrays/

## Escalar

São variáveis que aceitam apenas um valor específico, esse valor pode ser um número inteiro, real, natural ou complexo.

In [ ]:
#escalar que representa a tempetarura em graus Celsius
Temperatura = 33 
#escalar que representa a velocidade instantânea em m/s
Velocidade = 100 
#escalar que representa um valor monetário em R$ de um salário
salario = 1500.00 

## Vetor

Podem ser vistos como uma coleção de escalares, utilizados para representar dimensões mais elevadas.

Declaração

In [ ]:
import numpy as np

#vetor com duas dimensões
VT = np.array([27, 37]) 

#vetor com três dimensões
VV = np.array([20, 15, 100]) 

#vetor com quatro dimensões
VM = np.array([100, 205, 777, 111]) 

type(VM)

numpy.ndarray

Declaração e conversão com numpy

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = [[1,2],[3,4]]
B = [[1],[2]]

print (np.matrix(A))
print
print (np.matrix(B))

[[1 2]
 [3 4]]
[[1]
 [2]]


Somando elementos de 1 vetor.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([0, 1])

B = np.sum(A)

print(A)
print(B)

[0 1]
1


## Operações com vetores e escalares

Adição de escalar em um vetor

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([10, 20, 30])

print(A)

#Adiciona o escalar 2 a cada elemento do vetor A gerando o vetor B
B = A + 2

print(np.matrix(B))

[10 20 30]
[[12 22 32]]


Multiplicação de vetores por escalar.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([10, 20, 30])

print(A)

#Multiplica o escalar 3 a cada elemento do vetor A gerando o vetor B
B = A *  3

print(np.matrix(B))

[10 20 30]
[[30 60 90]]


## Operações entre vetores

Somando dois vetores

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([1, 2, 3])
B = np.array([3, 4, 5])

#soma o vetor A com o vetor B
C = A + B

print(C)

[4 6 8]


Produto de dois vetores

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([1, 2, 3])
B = np.array([3, 4, 5])

#multiplica o vetor A pelo vetor B
C= A * B

print(C)

[ 3  8 15]


Somando dois vetores.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([0,1])
B = np.array([2,3]) 

C = np.sum(A + B)

print(A)
print(B)
print(C)

[0 1]
[2 3]
6


## Matriz

Permitem representar uma coleção de vetores. Os elementos das matrizes podem ser números reais, complexos, expressões algébricas ou funções. Chamamos de diagonal principal os elementos onde i=m.

$$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
a_{21} & a_{22} & a_{23} & \cdots & a_{2n} \\
a_{31} & a_{32} & a_{33} & \cdots & a_{3n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & a_{m3} & \cdots & a_{mn}
\end{bmatrix}
$$


### Declaração de Matriz

Declarando uma matriz 1


In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0,1],[2,3]])

print(A)

[[0 1]
 [2 3]]


Declarando uma matriz 2

Outra forma de representar uma matriz seria através do método np.matrix().


In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.matrix([[0,1],[2,3]])

print(A)

[[0 1]
 [2 3]]


Tipo da matriz

In [ ]:
print(type(A))

<class 'numpy.matrix'>


### Manipulando a matriz

acessando um elemento da matriz

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.matrix([[0,1],[2,3]])

a11 = A[0,0]

print(a11)

0


Retornando a primeira linha


In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.matrix([[0,1],[2,3]])

A1n = A[0,:]

print(A1n)

[[0 1]]


 Retornando a segunda coluna

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.matrix([[0,1],[2,3]])

Am2 = A[:,1]

print(Am2)

[[1]
 [3]]


### Matriz quadrada

Uma matriz é considerada quadrada quando o número de linhas for igual ao número de columas, ou seja, m=n.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 

print(A)

[[0 1]
 [2 3]]


### Matriz diagonal

Uma matriz quadrada é considerada diagonal quando todos os elementos fora da diagonal principal forem nulos, ou seja, ij = 0 para todo i!=j.
Podemos representar uma matriz diagonal em python utilizando o método diag().

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.diag([10, 20, 30, 40, 50])

print(A)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


### Matriz triangular(superior e inferior)

Uma matriz é considerada **triangular superior** se amn = 0 quando m > n, ou seja, quandos os elementos abaixo da diagonal principal forem iguais a zero.

$$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} & a_{14}  & \cdots & a_{1n} \\
0 & a_{22} & a_{23} & a_{24} & \cdots & a_{2n} \\
0 & 0 & a_{33} & a_{34} & \cdots & a_{3n} \\
0 & 0 & 0 & a_{44} &\cdots & a_{4n} \\
\vdots & \vdots &a \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & 0 & \cdots & a_{nn}
\end{bmatrix}
$$


ma matriz é considerada **triangular inferior** se amn = 0 quando m < n, ou seja, quandos os elementos acima da diagonal principal forem iguais a zero.

$$
A = \begin{bmatrix}
a_{11} & 0 & 0 & 0  & \cdots & 0 \\
a_{21} & a_{22} & 0 & 0 & \cdots & 0 \\
a_{31} & a_{32} & a_{33} & 0 & \cdots & 0 \\
a_{41} & a_{42} & a_{43} & a_{44} &\cdots & 0 \\
\vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & a_{n3} & a_{n4} & \cdots & a_{nn}
\end{bmatrix}
$$

### Matriz linha

Podemos representar uma matriz linha por:

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

#Utilizando um conjunto a mais de colchetes ou parênteses
A = np.array([[10, 20, 30, -40]]) 

print(A)

[[ 10  20  30 -40]]


### Matriz coluna

Podemos representar uma matriz coluna por:

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[10],[20],[30],[40]])

print(A)

[[10]
 [20]
 [30]
 [40]]


Pode ser obtido a matriz coluna A obtendo a transposta da matriz linha B.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

#Utilizando um conjunto a mais de colchetes ou parênteses
B = np.array([[10, 20, 30, -40]]) 

print(B)

A = np.transpose(B)

print(A)

[[ 10  20  30 -40]]
[[ 10]
 [ 20]
 [ 30]
 [-40]]


### Matriz nula

É considerada nula se e somente se todos os seus elementos forem iguais a zero. Podemos definir uma matriz nula em python utilizando a função np.zeros passando a dimensão que desejamos.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.zeros([2,2])

print(A)

[[0. 0.]
 [0. 0.]]


### Matriz identidade

Uma matriz identidade é aquela na qual a diagonal principal possui todos os valores iguais a 1 e os demais valores iguais a zero. A matriz identidade é muito utilizada na resolução de sistemas de equações lineares. No python podemos representar uma matriz identidade através da função np.identity() passando como argumento a dimensão desejada.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

ID = np.identity(5)

print(ID)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Matriz transposta

A matriz transposta é uma matriz obtida através da troca ordenada de linhas por colunas de uma dada matriz, essa operação pode ser realizada utilizando a função np.transpose. A transposição não altera a diagonal principal de uma matriz quadrada.

Propriedades:

1. $ (A^T)^T = A $
2. $ (A + B)^T = A^T + B^T $
3. $ (cA)^T = cA^T $
4. $ (AB)^T = A^T B^T  $

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[10,20,30],[40,50,60]])

#mostra a matriz
print(A)

#Gera a transposta de A
At = np.transpose(A)

#mostra transposta
print(At)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


A matriz transposta também pode ser obtidade através do método .T.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[10,20,30],[40,50,60]])

#mostra a matriz
print(A)

#Gera a transposta de A
At = A.T

#mostra transposta
print(At)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


Vamos verificar a validação de cada uma das propriedades da transposta:

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array(([1,2],[3,4]))
B = np.array(([5,6],[7,8]))

print(A == B)

#Propriedade 1
print((A.T).T == A)

#Propriedade 2
print((A+B).T == A.T + B.T)

#Propriedade 3
print((7*A).T == 7*A.T)

#Propriedade 4
print((A*B).T == B.T*A.T)

[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


### Operações com escalar

Soma de elemento da matrizes por um escalar.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0,1],[2,3]])

print(A)

B = A + 2

print(B)

[[0 1]
 [2 3]]
[[2 3]
 [4 5]]


Multiplicação de elemento da matrizes por um escalar.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0,1],[2,3]])

print(A)

B = A * 3

print(B)

[[0 1]
 [2 3]]
[[0 3]
 [6 9]]


### Operações entre matrizes e vetores



Multiplicação de matriz e vetor

Na multiplicação de um vetor por uma matriz, precisamos verificar se as dimensões são compatíveis, ou seja, se o número de colunas são iguais.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([1, 2, 3]) #vetor

B = np.array(([10, 20, 30],[40, 50, 60]))

print(A)
print(B)

#multiplica o vetor A pela matriz B
C = A * B

print(C)

[1 2 3]
[[10 20 30]
 [40 50 60]]
[[ 10  40  90]
 [ 40 100 180]]


Somando matriz e vetor

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([1, 2, 3]) #vetor

B = np.array(([10, 20, 30],[40, 50, 60]))

print(A)
print(B)

#multiplica o vetor A pela matriz B
C = B+A

print(C)

[1 2 3]
[[10 20 30]
 [40 50 60]]
[[11 22 33]
 [41 52 63]]


Subtraindo matriz e vetor

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([1, 2, 3]) #vetor

B = np.array(([10, 20, 30],[40, 50, 60]))

print(A)
print(B)

#multiplica o vetor A pela matriz B
C = B-A

print(C)

[1 2 3]
[[10 20 30]
 [40 50 60]]
[[ 9 18 27]
 [39 48 57]]


Dividindo matriz e vetor

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([1, 2, 3]) #vetor

B = np.array(([10, 20, 30],[40, 50, 60]))

print(A)
print(B)

#multiplica o vetor A pela matriz B
C = B/A

print(C)

[1 2 3]
[[10 20 30]
 [40 50 60]]
[[10. 10. 10.]
 [40. 25. 20.]]


### Operações entre matrizes
Precisamos conferir se as dimensões são compatíveis para efetuar as operações matemáticas.

Somando duas matrizes

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

print(A)
print(B)

C = A + B

print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[3 5]
 [7 9]]


Subtraindo duas matrizes

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

print(A)
print(B)

C = B - A

print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[3 3]
 [3 3]]


Multiplicando duas matrizes 1

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

print(A)
print(B)

C = A * B

print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[ 0  4]
 [10 18]]


Multiplicando duas matrizes 2
 
A multiplicação entre os elementos das matrizes pode ser realizada através da função np.multiply().

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

print(A)
print(B)

C = np.multiply(A, B)

print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[ 0  4]
 [10 18]]



Obs: Só é possível realizar o produto entre duas matrizes se o número de colunas da primeira matriz for igual ao número de linhas da segunda. O produto entre matrizes pode ser feito através do método np.dot(m1,m2).

$$A_{mn} . B_{np} = (AB)_{mp}$$

No produto entre matrizes, cada elemento da linha da primeira coluna deve ser multiplicado e somado pelos correspondentes elementos da coluna da segunda matriz.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

print(A)
print(B)

C = np.dot(A, B)

print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[ 5  6]
 [21 26]]


Não temos comutatividade no produto entre matrizes, a ordem importa!

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

print(A)
print(B)

#invertido
C = np.dot(B, A)

print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[ 8 15]
 [12 23]]


Dividindo duas matrizes

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[1, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

print(A)
print(B)

C = B / A

print(C)

[[1 1]
 [2 3]]
[[3 4]
 [5 6]]
[[3.  4. ]
 [2.5 2. ]]


### Outras operações

Somando elementos de 1 matriz.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0,1],[2,3]])

B = np.sum(A)

print(A)
print(B)

[[0 1]
 [2 3]]
6


Multiplicando e somando 2 matrizes.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0,1],[2,3]])
B = np.array([[0,1],[2,3]]) 

C = np.sum(A * B)

print(A)
print(B)
print(C)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
14


Retorna a convolução linear discreta de dois vetores.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([1,2,3])        # 1 + 2x + 3x^2
B = np.array([4,5,6])        # 4 + 5x + 6x^2

C = np.convolve(A, B)        # (1 + 2x + 3x^2) * (4 + 5x + 6x^2)
#array([ 4, 13, 28, 27, 18]) # 4 + 13x + 28x^2 + 27x^3 + 18x^4

print(A)
print(B)
print(C)

[1 2 3]
[4 5 6]
[ 4 13 28 27 18]


Concatena duas matrizes.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

C = np.concatenate((A,B))

print(A)
print(B)
print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[0 1]
 [2 3]
 [3 4]
 [5 6]]


Concatena duas matrizes.

Seleciona o eixo.

axis = 0 eixo y.

axis = 1 eixo x.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

C = np.concatenate((A,B),axis=1)

print(A)
print(B)
print(C)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]
[[0 1 3 4]
 [2 3 5 6]]


função é usada para calcular uma das oito normas matriciais ou uma das normas vetoriais.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 

B = np.linalg.norm(A, axis=0)

print(A)
print(B)

B = np.linalg.norm(A, axis=1)

print(A)
print(B)

[[0 1]
 [2 3]]
[2.         3.16227766]
[[0 1]
 [2 3]]
[1.         3.60555128]


In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

Traço da matriz

O traço de uma matriz quadrada é a soma dos elementos da sua diagonal principal, o traço pode ser obtido através da função np.trace().

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[1, 2], [3, 4]]) 

print(A)

B = np.trace(A)

print(B)

[[1 2]
 [3 4]]
5


No caso de uma matriz não quadrada, a soma será da parte da diagonal principal referente a uma matriz quadrada, exemplo:

$$A_{23} = 
\begin{bmatrix}
{\color{Red}1} & 2 & 3 \\
3 & {\color{Red}4} & 5
\end{bmatrix}
$$

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]]) 

print(A)

B = np.trace(A)

print(B)

[[1 2 3]
 [3 4 5]]
5


Propriedade do traço:

1. $tr(A+B) = tr(A) + tr(B)$;

2. $tr(\lambda . A) = \lambda. tr(A)$;

3. O traço de uma matriz quadrada é igual ao traço de sua transposta;

4. $tr(AB) = tr(BA)$;

5. O traço de uma matriz simétrica é igual a soma dos seus valores próprios (autovalores). Uma matriz A é dita simétrica se ela for igual a sua transposta.



In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array(([1,1],[2,2]))
B = np.array(([3,3],[4,4]))

#Propriedade 1
np.trace(A+B) ==  np.trace(A) + np.trace(B)
print(np.trace(A+B) ==  np.trace(A) + np.trace(B))

#Propriedade 2
print(np.trace(5*A) == 5 * np.trace(A))

#Propriedade 3
print(np.trace(A) == np.trace(np.transpose(A)))

#Propriedade 4
print(np.trace(A*B) == np.trace(B*A))

True
True
True
True


### Inversa de uma matriz

Se o produto de duas matrizes resulta em uma matriz identidade, essa matriz possui uma inversa. A biblioteca Numpy possuí um pacote específico para trabalhar com álgebra linear, se chama numpy.lialg, no qual possuí a função inv() para calcular a inversa de uma matriz.

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

from numpy.linalg import inv

A = np.array(([1,2],[3,4]))
print(A)

B = inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Para verificar se a matriz B é inversa da matriz A:

In [ ]:
print(np.dot(B,A))

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


Propriedades da matriz inversa:

1. Se A for uma matriz inversa, a inversa de A também será invertível:

$$ (A^{-1})^{-1} = A $$

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array(([1.,2.],[3.,4.]))

#o retorno é falso por motivos de arredondamento
print(inv(inv(A)) == A)

[[False False]
 [False False]]


2. Se A e B forem matrizes invertíveis, então AB também é invertível:

$$ (AB^{-1})^{-1} = A^{-1} B^{-1} $$

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array(([1.,2.],[3.,4.]))
print("A=")
print(A)

B = inv(A)
print("B=")
print(B)

C = inv(A.dot(B))
print("C=")
print(C)

D = inv(B).dot(inv(A))
print("D=")
print(D)

A=
[[1. 2.]
 [3. 4.]]
B=
[[-2.   1. ]
 [ 1.5 -0.5]]
C=
[[ 1.0000000e+00  0.0000000e+00]
 [-8.8817842e-16  1.0000000e+00]]
D=
[[1.00000000e+00 9.86076132e-32]
 [8.88178420e-16 1.00000000e+00]]


3. Se A é uma matriz invertível, então a seguinte propriedade é válida:

$$ (A^T)^{-1} = (A^{-1})^T $$

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

A = np.array(([1.,2.],[3.,4.]))
print(A)

B = inv(A.T)
print(B)

C = (inv(A)).T

print(C)

[[1. 2.]
 [3. 4.]]
[[-2.   1.5]
 [ 1.  -0.5]]
[[-2.   1.5]
 [ 1.  -0.5]]


### Determinante de uma matriz

Para explicar o que são determinantes de matrizes, iremos analisar o sistema de equações lineares abaixo:

$$\begin{cases}
  a_{11}x_{1} & + & a_{12}x_{2} = b_{1} \\ 
  a_{21}x_{1} & + & a_{22}x_{2} = b_{2}\\ 
\end{cases}$$


Estamos à procura das incógnitas do sistema, x1 e x2. Para isso devemos isolar uma das variáveis e substituir na outra equação, ao final do processo iremos chegar em duas equações:

$$ x_{1} = \dfrac{b_{1} a_{22} - b_{2} a_{12}}{a_{11} a_{22} - a_{12} a_{21}} 
$$
-
$$
x_{2} = \dfrac{b_{2} a_{11} - b_{1} a_{21}}{a_{11} a_{22} - a_{12} a_{21}}
$$

Podemos notar que o denominador das equações x1 e x2 são os mesmos. Essas constantes que aparecem no denominador das matrizes são chamadas de determinantes de uma matriz. O determinante só pode ser calculado em uma matriz quadrada.

**Calculando o determinante**

A determinante de uma matriz 1x1, ou seja, de um escalar é o próprio escalar;
A determinante de uma matriz 2x2 é a multiplicação dos elementos da diagonal principal subtraído pela multiplicação dos elementos da diagonal secundária;
Para uma matriz 3x3, pode ser utilizado o método de Sarrus, exemplificado abaixo:Método de Sarrus
Podemos utilizar outros teoremas para encontrar a determinante de uma matriz, como por exemplo o teorema de Laplace, decomposição LU, eliminação gaussiana, entre outros.

A linguagem Python nos permite encontrar determinantes de matrizes através da função det().

Exemplo 1

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np
from numpy.linalg import det

A = np.array(([1,5],[2,3]))

det_A = det(A)

print(det_A)

-7.000000000000001


Exemplo 2

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np
from numpy.linalg import det

A = np.array(([1,2,4],[5,3,-1],[7,2,0]))

det_A = det(A)

print(det_A)

-56.00000000000002


Exemplo 3

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np
from numpy.linalg import det

B = np.array(([1,2,4,5,6,7],
              [5,3,-1,5,1,2],
              [7,2,0,1,4,9],
              [1,2,1,5,6,5],
              [-7,2,4,-1,6,6],
              [0,2,5,5,9,7]))

det_B = det(B)

print(det_B)

8184.000000000006


### Coseno Matriz

In [ ]:
#biblioteca de álgebra linear(matrizes)
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

A = np.array([[0, 1], [2, 3]]) 
B = np.array([[3, 4], [5, 6]]) 

C = cosine_similarity(A,B) 

print('A>')
print(A)
print('B>')
print(B)
print('C>', C)

D = np.array([[0, 1], [4, 5]]) 

E = cosine_similarity(A,D) 

print('A>')
print(A)
print('D>')
print(D)
print('E>', E)

A>
[[0 1]
 [2 3]]
B>
[[3 4]
 [5 6]]
C> [[0.8        0.76822128]
 [0.99846035 0.99430915]]
A>
[[0 1]
 [2 3]]
D>
[[0 1]
 [4 5]]
E> [[1.         0.78086881]
 [0.83205029 0.99624059]]
